import type { Metadata } from "next";
import { Montserrat, Roboto, Jost } from "next/font/google";
import "./globals.css";




export const metadata: Metadata = {
  title: "T-shirt shop",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
