import type { Metadata } from "next";
import { Montserrat, Roboto, Jost } from "next/font/google";
import "./globals.css";

const monoserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["cyrillic"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic"],

});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["cyrillic"],
})


export const metadata: Metadata = {
  title: "T-shirt shop",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${jost.variable} ${monoserrat.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
